$(document).ready(function(){
        $(".GENERAL").show();
        $("#GENERAL").addClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    $("#GENERAL").click(function(){
        $(".GENERAL").show();
        $("#GENERAL").addClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#WORLD").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").show();
        $("#WORLD").addClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#ART").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").show();
        $("#ART").addClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#ENTERTAIMENT").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").show();
        $("#ENTERTAIMENT").addClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#VIDEOGAMES").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").show();
        $("#VIDEOGAMES").addClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#POLITICS").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").show();
        $("#POLITICS").addClass('active');
        $(".OFF-TOPIC").hide();
        $("#OFF-TOPIC").removeClass('active');
    })
    $("#OFF-TOPIC").click(function(){
        $(".GENERAL").hide();
        $("#GENERAL").removeClass('active');
        $(".WORLD").hide();
        $("#WORLD").removeClass('active');
        $(".ART").hide();
        $("#ART").removeClass('active');
        $(".ENTERTAIMENT").hide();
        $("#ENTERTAIMENT").removeClass('active');
        $(".VIDEOGAMES").hide();
        $("#VIDEOGAMES").removeClass('active');
        $(".POLITICS").hide();
        $("#POLITICS").removeClass('active');
        $(".OFF-TOPIC").show();
        $("#OFF-TOPIC").addClass('active');
    })
});